language: ruby
rvm:
  - 2.1.2
  - 2.2.2
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
env:
  - CODECOV_TOKEN=58607149-bb8e-486c-baa7-165a0a76a0d0
branches:
  only:
    - "master"
    - "/^release-/"
before_install: gem install bundler
cache: bundler
sudo: false
git:
  depth: 1
