language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
matrix:
  allow_failures:
    - rvm: ruby-head
env:
  - CODECOV_TOKEN=58607149-bb8e-486c-baa7-165a0a76a0d0
branches:
  only:
    - "master"
    - "/^release-/"
before_install: gem install bundler
cache: bundler
sudo: false
git:
  depth: 1
