= D★Mark
Denis Defreyne <denis@stoneship.org>

image:http://img.shields.io/gem/v/d-mark.svg[Gem version, link="http://rubygems.org/gems/d-mark"]
image:http://img.shields.io/travis/ddfreyne/d-mark.svg[Build status, link="https://travis-ci.org/ddfreyne/d-mark"]
image:http://img.shields.io/codeclimate/github/ddfreyne/d-mark.svg[Code Climate, link="https://codeclimate.com/github/ddfreyne/d-mark"]
image:http://img.shields.io/codecov/c/github/ddfreyne/d-mark.svg[Code Coverage, link="https://codecov.io/github/ddfreyne/d-mark"]

_D★Mark_ is a language for marking up prose. It facilitates writing semantically meaningful text, without limiting itself to the semantics provided by HTML or Markdown.

If you’re a technical writer looking for a flexible markup language, D★Mark might be a good fit.

Here’s an example of D★Mark:

[source]
----
h1. D★Mark

para. D★Mark is a language for marking up prose. It facilitates writing semantically meaningful text, without limiting itself to the semantics provided by HTML or Markdown.

para. If you’re a technical writer looking for a flexible markup language, D★Mark might be a good fit.

h2. Goals

dl.
  dt. Be extensible
  dd. Define only the syntax of the markup language, and don’t bother with semantics. Do not define a vocabulary.

  dt. Be simple
  dd. Be easy to write, easy to read, and easy to parse. Be unambiguous. Be easy to syntax highlight.

  dt. Be compact
  dd. Introduce as little extra syntax as possible.
----

== Goals

Be extensible::
  Define only the syntax of the markup language, and don’t bother with semantics. Do not define a vocabulary.

Be simple::
  Be easy to write, easy to read, and easy to parse. Be unambiguous. Be easy to syntax highlight.

Be compact::
  Introduce as little extra syntax as possible.

== Syntax

D★Mark knows two constructs: _elements_ and _text_. An element has a name, attributes, and wrap elements and/or text in order to give them meaning. Text is just that—text.

An element in D★Mark can take two forms _block-level_ and _inline_:

Block form::
  An element in block form consists of the name of the element, a period, optionally attributes enclosed in rectangular brackets, a space character, and finally the content. For example:
+
[source]
----
para. This a paragraph; an element in block form containing some text.

note[only=web]. This is an example “note” element with an “only” attribute.
----

Inline form::
  Inside an element, text can be marked up using elements with the inline form. An element in inline form consists of a percentage sign, the name of the element, optionally attributes enclosed in rectangular brackets, and finally the content within braces. For example:
+
[source]
----
para. I am a paragraph with an %emph{amazing} inline element.
----

At the top level, D★Mark documents consists _only_ of elements in block form.

Elements in block form can be nested. To do so, indent the nested block two spaces deeper than the enclosing block. For example, the following defines a `list` element with three `item` elements inside it:

[source]
----
list[unordered].
  item. glob patterns
  item. regular expression patterns
  item. legacy patterns
----

The block element form can also include text on indented lines following the element. In this case, the content is not wrapped inside a nested block-level element. This is particularly useful for source code listing. For example:

[source]
----
listing[lang=ruby].
  identifier = Nanoc::Identifier.new('/about.md')

  identifier.without_ext
  # => "/about"

  identifier.ext
  # => "md"
----

An element in block form can always be expressed in inline form and vice versa, with the exception of a top-level element, which always needs to be in block form.

The characters `}`, `%` need to be escaped when used in plain text. To escape a character, prefix it with `%`. Thus, `%%` is the escaped form of `%`, and `%}` is the escaped form of `}`. Inside attributes, the characters `]` and `,` also need to be escaped; the same escaping method applies. For example:

[source]
----
para[kind=joke%, ha ha]. They say 20%% of all statistics are made up.
----

This is a `para` element with the `kind` set to `joke, ha ha`, and the content “They say 20% of all statistics are made up.”

=== Attributes

Both block and inline elements can also have attributes. Attributes are enclosed in square brackets after the element name, as a comma-separated list of key-value pairs separated by an equal sign. The value part, along with the equal sign, can be omitted, in which case the value will be equal to the key name.

For example:

* `%code[lang=ruby]{Nanoc::VERSION}` is an inline `code` element with the `lang` attribute set to `ruby`.

* `%only[web]{Refer to the release notes for details.}` is an inline `only` element with the `web` attribute set to `web`.

* `h2[id=donkey]. All about donkeys` is a block-level `h2` element with the `id` attribute set to `donkey`.

* `p[print]. This is a paragraph that only readers of the book will see.` is a block-level `para` element with the `print` attribute set to `print`.

== Comparison with other languages

D★Mark takes inspiration from a variety of other languages.

HTML::
  HTML is syntactically unambiguous, but comparatively more verbose than other languages. It also prescribes only a small set of elements, which makes it awkward to use for prose that requires more thorough markup. It is possible use `span` or `div` elements with custom classes, but this approach turns an already verbose language into something even more verbose.
+
[source,html]
----
<p>A glob pattern that matches every item is <span class="pattern attr-kind-glob">/**/*</span>.</p>
----
+
[source,d-mark]
----
para. A glob pattern that matches every item is %pattern[glob]{/**/*}.
----

XML::
  Similar to HTML, with the major difference that XML does not prescribe a set of elements.
+
[source,xml]
----
<para>A glob pattern that matches every item is <pattern kind="glob">/**/*</pattern>.</para>
----
+
[source,d-mark]
----
para. A glob pattern that matches every item is %pattern[glob]{/**/*}.
----

Markdown::
  Markdown has a compact syntax, but is complex and ambiguous, as evidenced by the many different mutually incompatible implementations. It prescribes a small set of elements (smaller even than HTML). It supports embedding raw HTML, which in theory makes it possible to combine the best of both worlds, but in practice leads to markup that is harder to read than either Markdown or HTML separately, and occasionally trips up the parser and syntax highlighter.
+
[source]
----
A glob pattern that matches every item is <span class="glob attr-kind-glob">/**/*</span>.
----
+
[source,d-mark]
----
para. A glob pattern that matches every item is %pattern[glob]{/**/*}.
----

AsciiDoc::
  AsciiDoc, along with its AsciiDoctor variant, are syntactically unambiguous, but complex languages. They prescribe a comparatively large set of elements which translates well to DocBook and HTML. They do not support custom markup or embedding raw HTML, which makes them harder t use for prose that requires more complex markup.
+
_(No example, as this example cannot be represented with AsciiDoc.)_

TeX, LaTeX::
  TeX is a turing-complete programming language, as opposed to a markup language, intended for typesetting. This makes it impractical for using it as the source for converting it to other formats. Its syntax is simple and compact, and served as an inspiration for D★Mark.
+
[source,latex]
----
A glob pattern that matches every item is \pattern[glob]{/**/*}.
----
+
[source,d-mark]
----
para. A glob pattern that matches every item is %pattern[glob]{/**/*}.
----

JSON, YAML::
  JSON and YAML are data interchange formats rather than markup languages, and thus are not well-suited for marking up prose.
+
[source,json]
----
[
  "A glob pattern that matches every item is ",
  ["pattern", {"kind": "glob"}, ["/**/*"]],
  "."
]
----
+
[source,d-mark]
----
para. A glob pattern that matches every item is %pattern[glob]{/**/*}.
----

== Samples

The `samples/` directory contains some sample D★Mark files. They can be processed by invoking the appropriate script with the same filename. For example:

....
% bundle exec ruby samples/trivial.rb
<p>I’m a <em>trivial</em> example!</p>
....

== Programmatic usage

Handling a D★Mark file consists of two stages: parsing and translating.

The parsing stage converts text into a list of nodes. Construct a parser with the tokens as input, and call `#run` to get the list of nodes.

[source,ruby]
----
content = File.read(ARGV[0])
nodes = DMark::Parser.new(content).run
----

The translating stage is not the responsibility of D★Mark. A translator is part of the domain of the source text, and D★Mark only deals with syntax rather than semantics. A translator will run over the tree and convert it into something else (usually another string). To do so, handle each node type (`DMark::ElementNode` or `String`). For example, the following translator will convert the tree into something that resembles XML:

[source,ruby]
----
class MyXMLLikeTranslator < DMark::Translator
  def handle(node)
    case node
    when String
      out << node
    when DMark::ElementNode
      out << "<#{node.name}>"
      handle_children(node)
      out << "</#{node.name}>"
    end
  end
end

result = MyXMLLikeTranslator.new(nodes).run
puts result
----
