source 'https://rubygems.org'

# Compiling
gem 'nanoc', '~> 4.9'
group 'nanoc' do
  gem 'nanoc-live', '~> 1.1'
end

# Viewing
gem 'adsf', '~> 1.5'
gem 'webrick', '~> 1.7'

gem 'd-mark', path: '..'

gem 'nokogiri'
gem 'rouge'
